# Generated by Django 2.2.20 on 2021-05-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210523_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_followed',
        ),
    ]
