# Generated by Django 2.2.20 on 2021-05-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_follow_is_followed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='followed',
        ),
    ]
