# Generated by Django 2.2.20 on 2021-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210524_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_followed',
            field=models.BooleanField(default=False),
        ),
    ]
